# Generated by Django 2.0.6 on 2019-05-22 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markname', models.CharField(max_length=20)),
                ('min_money', models.IntegerField()),
                ('max_money', models.IntegerField()),
                ('receive_money', models.CharField(max_length=10)),
                ('time_limit', models.CharField(max_length=10)),
                ('year_money', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=5)),
                ('make_time', models.TimeField()),
            ],
            options={
                'db_table': 'investment',
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_invest_money', models.IntegerField(default=0)),
                ('one_loan_money', models.IntegerField(default=0)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zx_app.Investment')),
            ],
            options={
                'db_table': 'relation',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('invcode', models.CharField(max_length=6)),
                ('invest_money', models.IntegerField(default=0)),
                ('loan_money', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='relation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zx_app.Users'),
        ),
        migrations.AddField(
            model_name='investment',
            name='user',
            field=models.ManyToManyField(through='zx_app.Relation', to='zx_app.Users'),
        ),
    ]
