# Generated by Django 2.0.6 on 2019-05-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zx_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=120),
        ),
    ]
