# Generated by Django 2.0.6 on 2019-05-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zx_app', '0002_auto_20190522_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='invest_money',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='loan_money',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
