# Generated by Django 2.2.1 on 2019-05-22 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markname', models.CharField(max_length=20)),
                ('min_money', models.IntegerField()),
                ('max_money', models.IntegerField()),
                ('receive_money', models.IntegerField()),
                ('time_limit', models.CharField(max_length=10)),
                ('year_money', models.IntegerField()),
                ('label', models.CharField(max_length=5)),
                ('make_time', models.TimeField()),
                ('project_money', models.IntegerField()),
                ('security_system', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'investment',
            },
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('borrow_money', models.IntegerField()),
                ('borrow_data', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('house_count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('borrow', models.CharField(max_length=50)),
                ('borrow_describe', models.CharField(max_length=50)),
                ('borrow_case', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pledge',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('invcode', models.CharField(max_length=6)),
                ('invest_money', models.IntegerField(default=0)),
                ('loan_money', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_invest_money', models.IntegerField(default=0)),
                ('one_loan_money', models.IntegerField(default=0)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Investment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Users')),
            ],
            options={
                'db_table': 'relation',
            },
        ),
        migrations.AddField(
            model_name='investment',
            name='user',
            field=models.ManyToManyField(through='myapp.Relation', to='myapp.Users'),
        ),
    ]
