# Generated by Django 2.2.1 on 2019-05-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='scale',
            field=models.IntegerField(null=True),
        ),
    ]
