# Generated by Django 2.2.1 on 2019-05-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_investment_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='level',
            field=models.CharField(default='低', max_length=10),
        ),
        migrations.AddField(
            model_name='users',
            name='number',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='users',
            name='use_money',
            field=models.IntegerField(default=0),
        ),
    ]
