# Generated by Django 2.2.1 on 2019-05-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190524_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='level',
            field=models.CharField(default='低', max_length=10),
        ),
    ]
