# Generated by Django 2.2.1 on 2019-05-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_users_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='number',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
