# Generated by Django 2.2.1 on 2019-05-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_users_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='use_money',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
