# Generated by Django 2.2.1 on 2019-05-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_users_use_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='use_money',
            field=models.IntegerField(default=0),
        ),
    ]
