# Generated by Django 2.2.1 on 2019-05-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190525_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_yh',
            field=models.IntegerField(default=None),
        ),
    ]
