# Generated by Django 2.2.1 on 2019-05-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_users_user_yh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_yh',
            field=models.IntegerField(default=None, max_length=30),
        ),
    ]
