# Generated by Django 2.2.1 on 2019-05-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20190527_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='invcode',
            field=models.CharField(default=0, max_length=4, verbose_name='邀请码'),
        ),
    ]
