# Generated by Django 2.2.1 on 2019-05-27 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20190527_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_yh',
        ),
    ]
