# Generated by Django 2.2.1 on 2019-05-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20190527_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='invcode',
            field=models.CharField(max_length=50, verbose_name='银行卡号'),
        ),
    ]
